version: "3"
services:
  db:
    image: postgres:latest
    networks:
      - eye
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 10s
      retries: 5
    volumes:
      - ./seed.sql:/sql/seed.sql

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eye
    volumes:
      - ./migrations/:/migrations/
    command: ["-database", $POSTGRES_URL, "-path", "migrations", "up"]

networks:
  eye:
